### ISSUE TITLE
'NoneType' object has no attribute 'rogerthat_chat_id'

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/plugin-intercom-support#4]
Happens a lot with topic "conversation.user.created"

```
'NoneType' object has no attribute 'rogerthat_chat_id' (/base/data/home/apps/e~tff-backend/20170922t215127.404293309553333993/framework/setup_functions.py:176)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/e~tff-backend/20170922t215127.404293309553333993/plugins/intercom_support/intercom_webhooks.py", line 52, in post
    handler(payload)
  File "/base/data/home/apps/e~tff-backend/20170922t215127.404293309553333993/plugins/intercom_support/intercom_webhooks.py", line 62, in conversation_user_created
    rogerthat_chat_id = ic.rogerthat_chat_id
AttributeError: 'NoneType' object has no attribute 'rogerthat_chat_id'
```

**Comment by lucasvanhalst** [comment]
Should have been fixed by ab4e42492adee44d6a85f582238fd3c2568f8f04 but it is not deployed yet
